config/routes.rb
Tom::Application.routes.draw do

  resources :phases

  get "pages/tables"

  resources :stamps

  resources :entities

  resources :foundries

  resources :technologies

  resources :categories

  resources :components

  resources :people

  resources :fundings

  resources :projects

  resources :references

  resources :comments

  resources :contractors

  resources :payments

  resources :milestones

  resources :meetings

  resources :key_people

  resources :deliverables

  get "deliverables/new"

  get "key_persons/new"

  get "pages/about"

  resources :activities, :key_people, :deliverables, :phases

end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/activity.rb
class Activity < ActiveRecord::Base
#  attr_accessible :title :nickname :abstract :contract :funding_id :funding_amount :startdate_id :enddate_id :project_id

  validate :title,    :presence => true
  validate :nickname, :presence => true

  belongs_to :project
  belongs_to :activity
  belongs_to :funding

  has_many :People, :through => :KeyPeople
  has_many :Entities, :through => :Contractors
  has_many :Phases,     :dependent => :destroy
  has_many :Meetings,     :dependent => :destroy
  has_many :Milestones,     :dependent => :destroy
  has_many :Comments,     :dependent => :destroy
  has_many :Components,     :dependent => :destroy
  has_many :Infos,  :dependent => :destroy
  has_many :MonthlyReports,  :dependent => :destroy
  has_many :Actions,     :dependent => :destroy

end


class Picture < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
end
 
class Employee < ActiveRecord::Base
  has_many :pictures, :as => :imageable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/component.rb
class Component < ActiveRecord::Base
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/foundry.rb
class Foundry < ActiveRecord::Base
end

app/models/funding.rb
class Funding < ActiveRecord::Base
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/key_person.rb
class KeyPerson < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to   :phase
  has_many     :deliverables
  has_many     :payments
  has_many     :meetings
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/phase.rb
class Phase < ActiveRecord::Base
  has_many :milestones
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/qlevel.rb
class Qlevel < ActiveRecord::Base
end

app/models/reference.rb
class Reference < ActiveRecord::Base
end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :stamp_id %><br />
    <%= f.number_field :stamp_id %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :activity_id %><br />
    <%= f.number_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :milestone_id %><br />
    <%= f.number_field :milestone_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/_short.html.erb
<% unless @object.empty? %>
<% @meetings = @object %>

<p>
  <b>Meetings:</b>
    <table>
      <tr><th> Title </th><th> Venue </th> </tr>
      <% @meetings.each do |meeting| %>
      <tr>
	<td><%= meeting.title =%></td>
	<td><%= meeting.venue =%></td>
      </tr>
      <% end %>
    </table>
</p>

<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Venue</th>
    <th>Stamp</th>
    <th>Number</th>
    <th>Activity</th>
    <th>Milestone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.title %></td>
    <td><%= meeting.venue %></td>
    <td><%= meeting.stamp_id %></td>
    <td><%= meeting.number %></td>
    <td><%= meeting.activity_id %></td>
    <td><%= meeting.milestone_id %></td>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @meeting.title %>
</p>

<p>
  <b>Venue:</b>
  <%= @meeting.venue %>
</p>

<p>
  <b>Stamp:</b>
  <%= @meeting.stamp_id %>
</p>

<p>
  <b>Number:</b>
  <%= @meeting.number %>
</p>

<p>
  <b>Activity:</b>
  <%= @meeting.activity_id %>
</p>

<p>
  <b>Milestone:</b>
  <%= @meeting.milestone_id %>
</p>


<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>