config/routes.rb
Tom::Application.routes.draw do

  resources :phases

  get "pages/tables"

  resources :stamps

  resources :entities

  resources :foundries

  resources :technologies

  resources :categories

  resources :components

  resources :people

  resources :fundings

  resources :projects

  resources :references

  resources :comments

  resources :contractors

  resources :payments

  resources :milestones

  resources :meetings

  resources :key_people

  resources :deliverables

  get "deliverables/new"

  get "key_persons/new"

  get "pages/about"

  resources :activities, :key_people, :deliverables, :phases

end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/activity.rb
class Activity < ActiveRecord::Base
#  attr_accessible :title :nickname :abstract :contract :funding_id :funding_amount :startdate_id :enddate_id :project_id

  validate :title,    :presence => true
  validate :nickname, :presence => true

  belongs_to :project
  belongs_to :activity
  belongs_to :funding

  has_many :People, :through => :KeyPeople
  has_many :Entities, :through => :Contractors
  has_many :Phases,     :dependent => :destroy
  has_many :Meetings,     :dependent => :destroy
  has_many :Milestones,     :dependent => :destroy
  has_many :Comments,     :dependent => :destroy
  has_many :Components,     :dependent => :destroy
  has_many :Infos,  :dependent => :destroy
  has_many :MonthlyReports,  :dependent => :destroy
  has_many :Actions,     :dependent => :destroy

end


class Picture < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
end
 
class Employee < ActiveRecord::Base
  has_many :pictures, :as => :imageable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/component.rb
class Component < ActiveRecord::Base
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/foundry.rb
class Foundry < ActiveRecord::Base
end

app/models/funding.rb
class Funding < ActiveRecord::Base
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/key_person.rb
class KeyPerson < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to   :phase
  has_many     :deliverables
  has_many     :payments
  has_many     :meetings
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/phase.rb
class Phase < ActiveRecord::Base
  has_many :milestones
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/qlevel.rb
class Qlevel < ActiveRecord::Base
end

app/models/reference.rb
class Reference < ActiveRecord::Base
end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  # GET /contractors
  # GET /contractors.json
  def index
    @contractors = Contractor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contractors }
    end
  end

  # GET /contractors/1
  # GET /contractors/1.json
  def show
    @contractor = Contractor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contractor }
    end
  end

  # GET /contractors/new
  # GET /contractors/new.json
  def new
    @contractor = Contractor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contractor }
    end
  end

  # GET /contractors/1/edit
  def edit
    @contractor = Contractor.find(params[:id])
  end

  # POST /contractors
  # POST /contractors.json
  def create
    @contractor = Contractor.new(params[:contractor])

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: 'Contractor was successfully created.' }
        format.json { render json: @contractor, status: :created, location: @contractor }
      else
        format.html { render action: "new" }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contractors/1
  # PUT /contractors/1.json
  def update
    @contractor = Contractor.find(params[:id])

    respond_to do |format|
      if @contractor.update_attributes(params[:contractor])
        format.html { redirect_to @contractor, notice: 'Contractor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractors/1
  # DELETE /contractors/1.json
  def destroy
    @contractor = Contractor.find(params[:id])
    @contractor.destroy

    respond_to do |format|
      format.html { redirect_to contractors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/contractors/_form.html.erb
<%= form_for(@contractor) do |f| %>
  <% if @contractor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
      <% @contractor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_id %><br />
    <%= f.number_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :entity_id %><br />
    <%= f.number_field :entity_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contractors/edit.html.erb
<h1>Editing contractor</h1>

<%= render 'form' %>

<%= link_to 'Show', @contractor %> |
<%= link_to 'Back', contractors_path %>

app/views/contractors/index.html.erb
<h1>Listing contractors</h1>

<table>
  <tr>
    <th>Activity</th>
    <th>Entity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contractors.each do |contractor| %>
  <tr>
    <td><%= contractor.activity_id %></td>
    <td><%= contractor.entity_id %></td>
    <td><%= link_to 'Show', contractor %></td>
    <td><%= link_to 'Edit', edit_contractor_path(contractor) %></td>
    <td><%= link_to 'Destroy', contractor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contractor', new_contractor_path %>

app/views/contractors/new.html.erb
<h1>New contractor</h1>

<%= render 'form' %>

<%= link_to 'Back', contractors_path %>

app/views/contractors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Activity:</b>
  <%= @contractor.activity_id %>
</p>

<p>
  <b>Entity:</b>
  <%= @contractor.entity_id %>
</p>


<%= link_to 'Edit', edit_contractor_path(@contractor) %> |
<%= link_to 'Back', contractors_path %>