config/routes.rb
Tom::Application.routes.draw do

  resources :phases

  get "pages/tables"

  resources :stamps

  resources :entities

  resources :foundries

  resources :technologies

  resources :categories

  resources :components

  resources :people

  resources :fundings

  resources :projects

  resources :references

  resources :comments

  resources :contractors

  resources :payments

  resources :milestones

  resources :meetings

  resources :key_people

  resources :deliverables

  get "deliverables/new"

  get "key_persons/new"

  get "pages/about"

  resources :activities, :key_people, :deliverables, :phases

end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/activity.rb
class Activity < ActiveRecord::Base
#  attr_accessible :title :nickname :abstract :contract :funding_id :funding_amount :startdate_id :enddate_id :project_id

  validate :title,    :presence => true
  validate :nickname, :presence => true

  belongs_to :project
  belongs_to :activity
  belongs_to :funding

  has_many :People, :through => :KeyPeople
  has_many :Entities, :through => :Contractors
  has_many :Phases,     :dependent => :destroy
  has_many :Meetings,     :dependent => :destroy
  has_many :Milestones,     :dependent => :destroy
  has_many :Comments,     :dependent => :destroy
  has_many :Components,     :dependent => :destroy
  has_many :Infos,  :dependent => :destroy
  has_many :MonthlyReports,  :dependent => :destroy
  has_many :Actions,     :dependent => :destroy

end


class Picture < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
end
 
class Employee < ActiveRecord::Base
  has_many :pictures, :as => :imageable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/component.rb
class Component < ActiveRecord::Base
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/foundry.rb
class Foundry < ActiveRecord::Base
end

app/models/funding.rb
class Funding < ActiveRecord::Base
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/key_person.rb
class KeyPerson < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to   :phase
  has_many     :deliverables
  has_many     :payments
  has_many     :meetings
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/phase.rb
class Phase < ActiveRecord::Base
  has_many :milestones
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/qlevel.rb
class Qlevel < ActiveRecord::Base
end

app/models/reference.rb
class Reference < ActiveRecord::Base
end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  # GET /references
  # GET /references.json
  def index
    @references = Reference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @references }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    @reference = Reference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/new
  # GET /references/new.json
  def new
    @reference = Reference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/1/edit
  def edit
    @reference = Reference.find(params[:id])
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(params[:reference])

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render json: @reference, status: :created, location: @reference }
      else
        format.html { render action: "new" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /references/1
  # PUT /references/1.json
  def update
    @reference = Reference.find(params[:id])

    respond_to do |format|
      if @reference.update_attributes(params[:reference])
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference = Reference.find(params[:id])
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url }
      format.json { head :ok }
    end
  end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for(@reference) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_id %><br />
    <%= f.number_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<h1>Listing references</h1>

<table>
  <tr>
    <th>Activity</th>
    <th>Title</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @references.each do |reference| %>
  <tr>
    <td><%= reference.activity_id %></td>
    <td><%= reference.title %></td>
    <td><%= reference.url %></td>
    <td><%= link_to 'Show', reference %></td>
    <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
    <td><%= link_to 'Destroy', reference, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<h1>New reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Activity:</b>
  <%= @reference.activity_id %>
</p>

<p>
  <b>Title:</b>
  <%= @reference.title %>
</p>

<p>
  <b>Url:</b>
  <%= @reference.url %>
</p>


<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>